In [1]:
import numpy as np 

In [3]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[6,7,8,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]]])


In [4]:
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [5]:
vector_t = vector.T 
print(vector_t)

[3 4 5 6]


In [6]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [7]:
print(matriz.shape)
print(matriz_t.shape)

(3, 2)
(2, 3)


In [8]:
tensor_t = tensor.T 
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 6 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 7 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 8 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [10]:
matriz_t_t = matriz_t.T
print(matriz_t_t == matriz)

[[ True  True]
 [ True  True]
 [ True  True]]


In [11]:
A = matriz 
B = matriz_t 

In [13]:
C = A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [16]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B 

print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [18]:
D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
